CREATE TABLE clients
(
    id                BIGSERIAL PRIMARY KEY,
    telegram_id       VARCHAR(255) UNIQUE NOT NULL,
    username          VARCHAR(255),
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    phone_number      VARCHAR(20),
    email             VARCHAR(255),
    registration_date TIMESTAMP,
    fisrt_activity    TIMESTAMP,
    last_activity     TIMESTAMP
);

CREATE TABLE chats
(
    id               BIGSERIAL PRIMARY KEY,
    client_id        BIGINT NOT NULL REFERENCES clients (id) ON DELETE CASCADE,
    telegram_chat_id BIGINT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_message_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (client_id, telegram_chat_id)
);

CREATE TABLE message_history
(
    id                  BIGSERIAL PRIMARY KEY,
    chat_id             BIGINT  NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    telegram_message_id BIGINT  NOT NULL,
    message_text        TEXT,
    message_type        VARCHAR(50)              DEFAULT 'text',
    from_bot            BOOLEAN NOT NULL,
    sent_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    media_file_id       VARCHAR(500), --?
    UNIQUE (chat_id, telegram_message_id)
);

CREATE TABLE service
(
    id          bigint       not null unique primary key generated by default as identity,
    name        varchar(100) not null,
    price       int          not null,
    photo       varchar      not null,
    time        varchar(3),
    category_id bigint       not null
);

CREATE TABLE category
(
    id   bigint       not null unique primary key generated by default as identity,
    name varchar(100) not null
);

CREATE TABLE visit
(
    id          BIGSERIAL PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients (id) ON DELETE CASCADE,
    service_id  BIGINT NOT NULL REFERENCES service (id) ON DELETE CASCADE,
    visit_date  TIMESTAMP
);

CREATE TABLE visit_history
(
    id                BIGSERIAL PRIMARY KEY,
    client_id         BIGINT NOT NULL REFERENCES clients (id) ON DELETE CASCADE,
    visit_from_date   TIMESTAMP,
    visit_to_date     TIMESTAMP,
    description       TEXT,
    status            VARCHAR(50),
    reminder_sent_24h BOOLEAN DEFAULT FALSE,
    reminder_sent_1h  BOOLEAN DEFAULT FALSE,
    confirmation_sent BOOLEAN DEFAULT FALSE
);

CREATE TABLE reminders
(
    id             BIGSERIAL PRIMARY KEY,
    chat_id        BIGINT                   NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    visit_id       BIGINT REFERENCES visit (id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status         VARCHAR(20) DEFAULT 'scheduled',
    message_text   TEXT                     NOT NULL
);

CREATE TABLE message_templates
(
    id            BIGSERIAL PRIMARY KEY,
    template_type VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    template_text TEXT         NOT NULL,
    variables     JSONB,
    is_active     BOOLEAN                  DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE clients IS 'Таблица клиентов бота';
COMMENT ON TABLE chats IS 'Таблица чатов/диалогов с клиентами';
COMMENT ON TABLE message_history IS 'История всех сообщений в чатах';
COMMENT ON TABLE visit_history IS 'История посещений/визитов клиентов';
COMMENT ON TABLE service IS 'Услуги, предоставляемые клиентам';
COMMENT ON TABLE category IS 'Категории услуг';
COMMENT ON TABLE reminders IS 'Система напоминаний и уведомлений';
COMMENT ON TABLE message_templates IS 'Шаблоны сообщений для напоминаний';

alter table service
    add foreign key (category_id)
        references category (id)
        on update restrict
        on delete restrict;

insert into category (name)
values ('Брови'),
       ('Ногти');

insert into service (name, price, photo, time, category_id)
values ('Ламинирование', 1000, 'https://goldenmandarin.ru/wp-content/uploads/2021/06/3.jpg', '30', 1),
       ('Коррекция', 800, 'https://example.com/brows2.jpg', '30', 1),
       ('Маникюр', 1200, 'https://example.com/nails1.jpg', '30', 2),
       ('Покрытие гель-лаком', 1500, 'https://example.com/nails2.jpg', '30', 2);